coverage:
  status:
    project:
      default:
        target: 0%
plugins:
  gcov: false
  xcode: false
  pycoverage: false

ignore:
  - "**/*_deps/**"
  - "**/tests/**"
  - "**/build/**"
  - "**/*.gcno"
  - "**/*.gcda"
  - "**/*.info"
  - "**/*.xml"
  - "**/*CompilerId*.c*"