coverage:
  status:
    project:
      default:
        target: 0%

ignore:
  - "**/*_deps/**/*"
  - "tests"
  - "build/**/*"
  - "**/*.gcno"
  - "**/*.gcda"
  - "**/*.info"
  - "**/*.xml"
  - "**/*CompilerId*.c*"

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: core
      name: Core
      paths:
        - "src/core/**/*"