coverage:
  status:
    project:
      default:
        target: 0%

ignore:
  - "**/*_deps/**/*"
  - "tests"
  - "build/**/*"
  - "**/*.gcno"
  - "**/*.gcda"
  - "**/*.info"
  - "**/*.xml"
  - "**/*CompilerId*.c*"