//
// Created by Mono on 23/5/2025.
//

#ifndef EXPORT_H
#define EXPORT_H

#if defined(LUMI_USE_STATIC_LIB)
#  include <Lumi/Lumi_static_export.h> // Generated by generate_export_header for static
#else
#  include <Lumi/Lumi_shared_export.h> // Generated by generate_export_header for shared
#endif

#endif //EXPORT_H
