name: Build and Deploy Documentation
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen
      - name: Set up Build Environment
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libwayland-dev wayland-protocols libxkbcommon-dev xorg-dev clang lld llvm
          version: 1.0
          execute_install_scripts: true
      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - name: Build Documentation
        run: |
          cmake --workflow --preset=ci-workflow-docs
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4