name: Build and Deploy Documentation
on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
  docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up Build Environment
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wget graphviz
          version: 1.1
          execute_install_scripts: true
      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.14.0"
      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest
      - name: Build Documentation
        run: |
          cmake --workflow --preset=ci-workflow-docs
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
